name: Ejecucion de Tests con Selenium

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          gradle-version: '8.1.1'
      - name: Build with Gradle
        run: gradle test -Dcucumber.filter.tags="@Saucedemo" -DwebDriver=firefox -DheadlessMode=true -DwindowSize=800x1300 -DfullSteps=true --info
      - uses: actions/upload-artifact@v3 
        with:
          name: html report chrome
          path: app/test-reports/
