name: ejecucion de tests con selenium
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: set up jdk 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          gradle-version: '8.1.1'
      - name: build with gradle chrome @saucedemo
        run: gradle test -dcucumber.filter.tags="@saucedemo" -dwebdriver=chrome -dheadlessmode=true -dwindowsize=800x1300 -dfullsteps=true # --info
      - name: build with gradle firefox @plexusnewsletter
        run: gradle test -dcucumber.filter.tags="@plexusnewsletter" -dwebdriver=firefox -dheadlessmode=true -dwindowsize=800x1300 -dfullsteps=true # --info
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.gh_token }}
          path: "**/report/cucumber-report.json"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: html report chrome
          path: app/test-reports/

